

traffic:
  outputs:
    dev:
      dbname: postgres
      host: postgres
      pass: postgres
      port: 5432
      schema: models
      threads: 4
      type: postgres
      user: postgres
  target: dev
